/* ═══════════════════════════════════════════════
   Template Studio — Template Definitions
═══════════════════════════════════════════════ */

window.TEMPLATES = {
  resumes: [
    {
      id: 'resume-classic',
      name: 'Classic Professional',
      niche: 'resumes',
      tag: 'Best Seller',
      palette: { primary: '#1A1A2E', accent: '#E94560', secondary: '#16213E', light: '#F5F5F5', muted: '#888888' },
      description: 'Timeless sidebar layout with bold accent. Perfect for corporate & finance roles.',
      fields: [
        { id: 'name',       label: 'Full Name',       type: 'text',     placeholder: 'Alexandra Chen' },
        { id: 'title',      label: 'Job Title',       type: 'text',     placeholder: 'Senior Product Manager' },
        { id: 'email',      label: 'Email',           type: 'text',     placeholder: 'alex@email.com' },
        { id: 'phone',      label: 'Phone',           type: 'text',     placeholder: '(555) 000-0000' },
        { id: 'location',   label: 'Location',        type: 'text',     placeholder: 'San Francisco, CA' },
        { id: 'linkedin',   label: 'LinkedIn',        type: 'text',     placeholder: 'linkedin.com/in/alex' },
        { id: 'summary',    label: 'Professional Summary', type: 'textarea', placeholder: 'Driven professional with 8+ years...' },
        { id: 'exp1title',  label: 'Job Title #1',    type: 'text',     placeholder: 'Senior PM' },
        { id: 'exp1co',     label: 'Company #1',      type: 'text',     placeholder: 'Acme Corp' },
        { id: 'exp1dates',  label: 'Dates #1',        type: 'text',     placeholder: '2021 – Present' },
        { id: 'exp1desc',   label: 'Responsibilities #1', type: 'textarea', placeholder: '• Led cross-functional team of 12\n• Increased revenue by 34%' },
        { id: 'exp2title',  label: 'Job Title #2',    type: 'text',     placeholder: 'Product Manager' },
        { id: 'exp2co',     label: 'Company #2',      type: 'text',     placeholder: 'TechStart Inc' },
        { id: 'exp2dates',  label: 'Dates #2',        type: 'text',     placeholder: '2018 – 2021' },
        { id: 'exp2desc',   label: 'Responsibilities #2', type: 'textarea', placeholder: '• Launched 3 major product features\n• Managed $2M product budget' },
        { id: 'skills',     label: 'Skills (comma-separated)', type: 'text', placeholder: 'Product Strategy, Agile, SQL, Figma' },
        { id: 'education',  label: 'Education',       type: 'text',     placeholder: 'B.S. Computer Science — MIT — 2018' },
        { id: 'certs',      label: 'Certifications',  type: 'text',     placeholder: 'PMP, Scrum Master' },
      ]
    },
    {
      id: 'resume-modern',
      name: 'Modern Minimal',
      niche: 'resumes',
      tag: 'Clean',
      palette: { primary: '#0A3D62', accent: '#F0A500', secondary: '#1A5276', light: '#EBF5FB', muted: '#7FB3D3' },
      description: 'Clean two-column design with golden highlights. Ideal for tech & creative fields.',
      fields: [
        { id: 'name',       label: 'Full Name',       type: 'text',     placeholder: 'Jordan Rivera' },
        { id: 'title',      label: 'Job Title',       type: 'text',     placeholder: 'Full Stack Developer' },
        { id: 'email',      label: 'Email',           type: 'text',     placeholder: 'jordan@dev.io' },
        { id: 'phone',      label: 'Phone',           type: 'text',     placeholder: '(555) 123-4567' },
        { id: 'location',   label: 'Location',        type: 'text',     placeholder: 'Austin, TX' },
        { id: 'github',     label: 'GitHub / Portfolio', type: 'text',  placeholder: 'github.com/jordan' },
        { id: 'summary',    label: 'About Me',        type: 'textarea', placeholder: 'Full-stack engineer with passion for...' },
        { id: 'exp1title',  label: 'Job Title #1',    type: 'text',     placeholder: 'Lead Developer' },
        { id: 'exp1co',     label: 'Company #1',      type: 'text',     placeholder: 'StartupXYZ' },
        { id: 'exp1dates',  label: 'Dates #1',        type: 'text',     placeholder: '2022 – Present' },
        { id: 'exp1desc',   label: 'Achievements #1', type: 'textarea', placeholder: '• Built microservices architecture\n• Reduced API latency by 60%' },
        { id: 'exp2title',  label: 'Job Title #2',    type: 'text',     placeholder: 'Software Engineer' },
        { id: 'exp2co',     label: 'Company #2',      type: 'text',     placeholder: 'BigTech Co' },
        { id: 'exp2dates',  label: 'Dates #2',        type: 'text',     placeholder: '2019 – 2022' },
        { id: 'exp2desc',   label: 'Achievements #2', type: 'textarea', placeholder: '• Shipped 15+ product features\n• Mentored 4 junior engineers' },
        { id: 'skills',     label: 'Tech Skills',     type: 'text',     placeholder: 'React, Node.js, Python, AWS, Docker' },
        { id: 'education',  label: 'Education',       type: 'text',     placeholder: 'B.S. Software Engineering — UT Austin — 2019' },
        { id: 'projects',   label: 'Key Projects',    type: 'textarea', placeholder: 'Open-source CLI tool — 2k GitHub stars' },
      ]
    },
    {
      id: 'resume-creative',
      name: 'Creative Bold',
      niche: 'resumes',
      tag: 'Stand Out',
      palette: { primary: '#4A0E2B', accent: '#E91E8C', secondary: '#6D1B46', light: '#FFF0F7', muted: '#C06090' },
      description: 'Striking magenta-accented design. Perfect for designers, marketers & creatives.',
      fields: [
        { id: 'name',       label: 'Full Name',       type: 'text',     placeholder: 'Morgan Blake' },
        { id: 'title',      label: 'Role / Tagline',  type: 'text',     placeholder: 'Brand Designer & Visual Storyteller' },
        { id: 'email',      label: 'Email',           type: 'text',     placeholder: 'morgan@design.co' },
        { id: 'phone',      label: 'Phone',           type: 'text',     placeholder: '(555) 987-6543' },
        { id: 'location',   label: 'Location',        type: 'text',     placeholder: 'Brooklyn, NY' },
        { id: 'portfolio',  label: 'Portfolio URL',   type: 'text',     placeholder: 'morganblake.design' },
        { id: 'summary',    label: 'Creative Statement', type: 'textarea', placeholder: 'Obsessed with the intersection of...' },
        { id: 'exp1title',  label: 'Role #1',         type: 'text',     placeholder: 'Senior Brand Designer' },
        { id: 'exp1co',     label: 'Studio #1',       type: 'text',     placeholder: 'Studio Neon' },
        { id: 'exp1dates',  label: 'Dates #1',        type: 'text',     placeholder: '2020 – Present' },
        { id: 'exp1desc',   label: 'Work #1',         type: 'textarea', placeholder: '• Rebranded 12 clients — avg +40% engagement\n• Led visual identity for Series B campaigns' },
        { id: 'exp2title',  label: 'Role #2',         type: 'text',     placeholder: 'Graphic Designer' },
        { id: 'exp2co',     label: 'Studio #2',       type: 'text',     placeholder: 'Agency M' },
        { id: 'exp2dates',  label: 'Dates #2',        type: 'text',     placeholder: '2017 – 2020' },
        { id: 'exp2desc',   label: 'Work #2',         type: 'textarea', placeholder: '• Delivered 200+ assets for Fortune 500 brands\n• Designed award-winning packaging' },
        { id: 'tools',      label: 'Tools & Software', type: 'text',    placeholder: 'Figma, Illustrator, After Effects, Blender' },
        { id: 'education',  label: 'Education',       type: 'text',     placeholder: 'BFA Graphic Design — Parsons — 2017' },
        { id: 'awards',     label: 'Awards / Recognition', type: 'text', placeholder: 'Awwwards SOTD 2023, Cannes Shortlist' },
      ]
    }
  ],
  planners: [
    {
      id: 'planner-weekly',
      name: 'Weekly Planner',
      niche: 'planners',
      tag: 'Popular',
      palette: { primary: '#2D4A22', accent: '#8BC34A', secondary: '#1B2E14', light: '#F1F8E9', muted: '#7A9E6A' },
      description: '7-column time-blocked weekly view with goals and notes section.',
      fields: [
        { id: 'week',        label: 'Week of',              type: 'text',     placeholder: 'January 6 – 12, 2025' },
        { id: 'year',        label: 'Year',                 type: 'text',     placeholder: '2025' },
        { id: 'goal1',       label: 'Goal #1 this week',    type: 'text',     placeholder: 'Finish project proposal' },
        { id: 'goal2',       label: 'Goal #2 this week',    type: 'text',     placeholder: 'Exercise 4x' },
        { id: 'goal3',       label: 'Goal #3 this week',    type: 'text',     placeholder: 'Read 50 pages' },
        { id: 'affirmation', label: 'Weekly Affirmation',   type: 'text',     placeholder: 'I am focused and productive' },
        { id: 'notes',       label: 'Notes / Brain Dump',   type: 'textarea', placeholder: 'Ideas, reminders, anything...' },
      ]
    },
    {
      id: 'planner-monthly',
      name: 'Monthly Calendar',
      niche: 'planners',
      tag: 'Auto-dated',
      palette: { primary: '#0A3D62', accent: '#F0A500', secondary: '#1A5276', light: '#EBF5FB', muted: '#7FB3D3' },
      description: 'Auto-generates current month grid with goal tracker section.',
      fields: [
        { id: 'month',     label: 'Month (blank = current)', type: 'text',   placeholder: 'Leave blank for auto' },
        { id: 'year',      label: 'Year (blank = current)',  type: 'text',   placeholder: 'Leave blank for auto' },
        { id: 'theme',     label: 'Monthly Theme',           type: 'text',   placeholder: 'Health & Wellness' },
        { id: 'goal1',     label: 'Monthly Goal #1',         type: 'text',   placeholder: 'Run a 5K' },
        { id: 'goal2',     label: 'Monthly Goal #2',         type: 'text',   placeholder: 'Save $500' },
        { id: 'goal3',     label: 'Monthly Goal #3',         type: 'text',   placeholder: 'Read 2 books' },
        { id: 'intention', label: 'Monthly Intention',       type: 'text',   placeholder: 'Be present in every moment' },
      ]
    },
    {
      id: 'planner-daily',
      name: 'Daily Productivity',
      niche: 'planners',
      tag: 'Deep Work',
      palette: { primary: '#1A1A2E', accent: '#E94560', secondary: '#16213E', light: '#F5F5F5', muted: '#888888' },
      description: 'Hourly schedule (6AM–10PM) + priorities, habits, gratitude & brain dump.',
      fields: [
        { id: 'date',       label: 'Date',                   type: 'text',     placeholder: 'Monday, January 6, 2025' },
        { id: 'mood',       label: 'Mood (1–5)',             type: 'text',     placeholder: '4' },
        { id: 'priority1',  label: 'Top Priority #1',        type: 'text',     placeholder: 'Complete design mockups' },
        { id: 'priority2',  label: 'Top Priority #2',        type: 'text',     placeholder: 'Respond to client emails' },
        { id: 'priority3',  label: 'Top Priority #3',        type: 'text',     placeholder: '30-min workout' },
        { id: 'habit1',     label: 'Habit #1',               type: 'text',     placeholder: 'Morning meditation' },
        { id: 'habit2',     label: 'Habit #2',               type: 'text',     placeholder: 'Drink 8 glasses of water' },
        { id: 'habit3',     label: 'Habit #3',               type: 'text',     placeholder: 'No social media before 10am' },
        { id: 'grateful1',  label: 'Grateful for #1',        type: 'text',     placeholder: 'My health' },
        { id: 'grateful2',  label: 'Grateful for #2',        type: 'text',     placeholder: 'A good nights sleep' },
        { id: 'grateful3',  label: 'Grateful for #3',        type: 'text',     placeholder: 'My support system' },
        { id: 'brain',      label: 'Brain Dump',             type: 'textarea', placeholder: 'Anything on your mind...' },
        { id: 'reflection', label: 'End of Day Reflection',  type: 'textarea', placeholder: 'What went well? What to improve?' },
      ]
    }
  ],
  finance: [
    {
      id: 'finance-budget',
      name: 'Monthly Budget Tracker',
      niche: 'finance',
      tag: 'Essential',
      palette: { primary: '#0A3D62', accent: '#F0A500', secondary: '#1A5276', light: '#EBF5FB', muted: '#7FB3D3' },
      description: 'Complete income + expense tracker with 15 categories and net balance.',
      fields: [
        { id: 'month',         label: 'Month / Year',         type: 'text',     placeholder: 'January 2025' },
        { id: 'income1',       label: 'Primary Income ($)',   type: 'text',     placeholder: '5500' },
        { id: 'income2',       label: 'Side Income ($)',      type: 'text',     placeholder: '800' },
        { id: 'income3',       label: 'Other Income ($)',     type: 'text',     placeholder: '200' },
        { id: 'housing',       label: 'Housing ($)',          type: 'text',     placeholder: '1500' },
        { id: 'utilities',     label: 'Utilities ($)',        type: 'text',     placeholder: '150' },
        { id: 'groceries',     label: 'Groceries ($)',        type: 'text',     placeholder: '400' },
        { id: 'transport',     label: 'Transportation ($)',   type: 'text',     placeholder: '250' },
        { id: 'insurance',     label: 'Insurance ($)',        type: 'text',     placeholder: '200' },
        { id: 'subscriptions', label: 'Subscriptions ($)',    type: 'text',     placeholder: '80' },
        { id: 'entertainment', label: 'Entertainment ($)',    type: 'text',     placeholder: '150' },
        { id: 'dining',        label: 'Dining Out ($)',       type: 'text',     placeholder: '200' },
        { id: 'healthcare',    label: 'Healthcare ($)',       type: 'text',     placeholder: '100' },
        { id: 'savings',       label: 'Savings ($)',          type: 'text',     placeholder: '500' },
        { id: 'debt',          label: 'Debt Payments ($)',    type: 'text',     placeholder: '300' },
        { id: 'misc',          label: 'Miscellaneous ($)',    type: 'text',     placeholder: '100' },
        { id: 'notes',         label: 'Financial Notes',     type: 'textarea', placeholder: 'Key observations this month...' },
      ]
    },
    {
      id: 'finance-savings',
      name: 'Savings Goal Planner',
      niche: 'finance',
      tag: 'Motivating',
      palette: { primary: '#2D4A22', accent: '#8BC34A', secondary: '#1B2E14', light: '#F1F8E9', muted: '#7A9E6A' },
      description: '8 goal slots with visual progress bars, target amounts and deadlines.',
      fields: [
        { id: 'g1name',   label: 'Goal #1 Name',           type: 'text',  placeholder: 'Emergency Fund' },
        { id: 'g1target', label: 'Goal #1 Target ($)',      type: 'text',  placeholder: '10000' },
        { id: 'g1saved',  label: 'Goal #1 Saved ($)',       type: 'text',  placeholder: '3500' },
        { id: 'g1date',   label: 'Goal #1 Target Date',    type: 'text',  placeholder: 'Dec 2025' },
        { id: 'g2name',   label: 'Goal #2 Name',           type: 'text',  placeholder: 'Vacation Fund' },
        { id: 'g2target', label: 'Goal #2 Target ($)',      type: 'text',  placeholder: '3000' },
        { id: 'g2saved',  label: 'Goal #2 Saved ($)',       type: 'text',  placeholder: '900' },
        { id: 'g2date',   label: 'Goal #2 Target Date',    type: 'text',  placeholder: 'Aug 2025' },
        { id: 'g3name',   label: 'Goal #3 Name',           type: 'text',  placeholder: 'New Car' },
        { id: 'g3target', label: 'Goal #3 Target ($)',      type: 'text',  placeholder: '8000' },
        { id: 'g3saved',  label: 'Goal #3 Saved ($)',       type: 'text',  placeholder: '2200' },
        { id: 'g3date',   label: 'Goal #3 Target Date',    type: 'text',  placeholder: 'Jun 2026' },
        { id: 'g4name',   label: 'Goal #4 Name',           type: 'text',  placeholder: 'Home Down Payment' },
        { id: 'g4target', label: 'Goal #4 Target ($)',      type: 'text',  placeholder: '50000' },
        { id: 'g4saved',  label: 'Goal #4 Saved ($)',       type: 'text',  placeholder: '12000' },
        { id: 'g4date',   label: 'Goal #4 Target Date',    type: 'text',  placeholder: 'Dec 2027' },
        { id: 'monthly',  label: 'Monthly Savings Budget ($)', type: 'text', placeholder: '800' },
        { id: 'notes',    label: 'Strategy Notes',         type: 'textarea', placeholder: 'Automate transfers, cut subscriptions...' },
      ]
    },
    {
      id: 'finance-debt',
      name: 'Debt Payoff Tracker',
      niche: 'finance',
      tag: 'Freedom',
      palette: { primary: '#4A0E2B', accent: '#E91E8C', secondary: '#6D1B46', light: '#FFF0F7', muted: '#C06090' },
      description: 'Track up to 4 debts with avalanche/snowball strategy selector.',
      fields: [
        { id: 'strategy',  label: 'Strategy (Avalanche / Snowball)', type: 'text', placeholder: 'Avalanche' },
        { id: 'd1name',    label: 'Debt #1 Name',          type: 'text',  placeholder: 'Chase Sapphire Card' },
        { id: 'd1balance', label: 'Debt #1 Balance ($)',   type: 'text',  placeholder: '4500' },
        { id: 'd1rate',    label: 'Debt #1 Interest %',   type: 'text',  placeholder: '24.99' },
        { id: 'd1min',     label: 'Debt #1 Min Payment',  type: 'text',  placeholder: '90' },
        { id: 'd2name',    label: 'Debt #2 Name',          type: 'text',  placeholder: 'Student Loan' },
        { id: 'd2balance', label: 'Debt #2 Balance ($)',   type: 'text',  placeholder: '18000' },
        { id: 'd2rate',    label: 'Debt #2 Interest %',   type: 'text',  placeholder: '5.8' },
        { id: 'd2min',     label: 'Debt #2 Min Payment',  type: 'text',  placeholder: '200' },
        { id: 'd3name',    label: 'Debt #3 Name',          type: 'text',  placeholder: 'Car Loan' },
        { id: 'd3balance', label: 'Debt #3 Balance ($)',   type: 'text',  placeholder: '9800' },
        { id: 'd3rate',    label: 'Debt #3 Interest %',   type: 'text',  placeholder: '7.2' },
        { id: 'd3min',     label: 'Debt #3 Min Payment',  type: 'text',  placeholder: '285' },
        { id: 'd4name',    label: 'Debt #4 Name',          type: 'text',  placeholder: 'Medical Bill' },
        { id: 'd4balance', label: 'Debt #4 Balance ($)',   type: 'text',  placeholder: '1200' },
        { id: 'd4rate',    label: 'Debt #4 Interest %',   type: 'text',  placeholder: '0' },
        { id: 'd4min',     label: 'Debt #4 Min Payment',  type: 'text',  placeholder: '50' },
        { id: 'extra',     label: 'Extra Monthly Payment', type: 'text', placeholder: '300' },
        { id: 'notes',     label: 'Motivation / Notes',   type: 'textarea', placeholder: 'Why I am getting debt free...' },
      ]
    }
  ],
  social: [
    {
      id: 'social-calendar',
      name: '30-Day Content Calendar',
      niche: 'social',
      tag: 'Plan Ahead',
      palette: { primary: '#4A0E2B', accent: '#E91E8C', secondary: '#6D1B46', light: '#FFF0F7', muted: '#C06090' },
      description: '30-day grid with platform tracking for IG, TikTok, YouTube, Facebook & LinkedIn.',
      fields: [
        { id: 'month',     label: 'Month',               type: 'text',     placeholder: 'January 2025' },
        { id: 'niche',     label: 'Content Niche',       type: 'text',     placeholder: 'Personal Finance Tips' },
        { id: 'pillar1',   label: 'Content Pillar #1',   type: 'text',     placeholder: 'Educational' },
        { id: 'pillar2',   label: 'Content Pillar #2',   type: 'text',     placeholder: 'Entertaining' },
        { id: 'pillar3',   label: 'Content Pillar #3',   type: 'text',     placeholder: 'Inspirational' },
        { id: 'platforms', label: 'Active Platforms',    type: 'text',     placeholder: 'Instagram, TikTok, YouTube' },
        { id: 'cta',       label: 'Monthly CTA Goal',    type: 'text',     placeholder: 'Drive 500 email signups' },
        { id: 'notes',     label: 'Campaign Notes',      type: 'textarea', placeholder: 'Key themes, launches, collabs...' },
      ]
    },
    {
      id: 'social-strategy',
      name: 'Platform Strategy Planner',
      niche: 'social',
      tag: 'Grow Faster',
      palette: { primary: '#1A1A2E', accent: '#E94560', secondary: '#16213E', light: '#F5F5F5', muted: '#888888' },
      description: '4-platform deep-dive: Instagram, TikTok, YouTube & LinkedIn strategy cards.',
      fields: [
        { id: 'ig_niche',   label: 'Instagram Niche',      type: 'text',  placeholder: 'Minimalist lifestyle' },
        { id: 'ig_freq',    label: 'IG Post Frequency',    type: 'text',  placeholder: '5x/week feed + daily stories' },
        { id: 'ig_pillars', label: 'IG Content Pillars',   type: 'text',  placeholder: 'Styling, travel, productivity' },
        { id: 'ig_cta',     label: 'IG CTA / Bio Link',    type: 'text',  placeholder: 'Link to newsletter' },
        { id: 'tt_niche',   label: 'TikTok Niche',         type: 'text',  placeholder: 'Finance tips for millennials' },
        { id: 'tt_freq',    label: 'TikTok Frequency',     type: 'text',  placeholder: '1-2x daily' },
        { id: 'tt_hook',    label: 'TikTok Hook Formula',  type: 'text',  placeholder: 'Nobody talks about this...' },
        { id: 'yt_niche',   label: 'YouTube Niche',        type: 'text',  placeholder: 'Long-form budgeting tutorials' },
        { id: 'yt_freq',    label: 'YouTube Frequency',    type: 'text',  placeholder: '2x per month' },
        { id: 'yt_series',  label: 'YouTube Series',       type: 'text',  placeholder: 'Debt-Free Journey Ep 1-12' },
        { id: 'li_niche',   label: 'LinkedIn Niche',       type: 'text',  placeholder: 'B2B SaaS growth strategies' },
        { id: 'li_freq',    label: 'LinkedIn Frequency',   type: 'text',  placeholder: '3x/week text posts' },
        { id: 'li_lead',    label: 'LinkedIn Lead Magnet', type: 'text',  placeholder: 'Free growth audit' },
        { id: 'notes',      label: 'Cross-Platform Notes', type: 'textarea', placeholder: 'Repurposing strategy, collab ideas...' },
      ]
    },
    {
      id: 'social-analytics',
      name: 'Analytics Tracker',
      niche: 'social',
      tag: 'Data Driven',
      palette: { primary: '#0A3D62', accent: '#F0A500', secondary: '#1A5276', light: '#EBF5FB', muted: '#7FB3D3' },
      description: 'Track 10 key metrics across 6 platforms monthly with insights section.',
      fields: [
        { id: 'period',     label: 'Reporting Period',         type: 'text',  placeholder: 'January 2025' },
        { id: 'ig_follow',  label: 'Instagram Followers',      type: 'text',  placeholder: '12400' },
        { id: 'ig_reach',   label: 'Instagram Reach',          type: 'text',  placeholder: '45000' },
        { id: 'ig_eng',     label: 'Instagram Engagement %',   type: 'text',  placeholder: '3.8' },
        { id: 'tt_follow',  label: 'TikTok Followers',         type: 'text',  placeholder: '8900' },
        { id: 'tt_views',   label: 'TikTok Video Views',       type: 'text',  placeholder: '124000' },
        { id: 'tt_eng',     label: 'TikTok Engagement %',      type: 'text',  placeholder: '7.2' },
        { id: 'yt_subs',    label: 'YouTube Subscribers',      type: 'text',  placeholder: '3200' },
        { id: 'yt_views',   label: 'YouTube Views',            type: 'text',  placeholder: '18500' },
        { id: 'yt_watch',   label: 'YouTube Watch Time (hrs)', type: 'text',  placeholder: '940' },
        { id: 'li_follow',  label: 'LinkedIn Followers',       type: 'text',  placeholder: '2800' },
        { id: 'li_impress', label: 'LinkedIn Impressions',     type: 'text',  placeholder: '32000' },
        { id: 'best',       label: 'Best Performing Post',     type: 'text',  placeholder: '5 money rules reel - 89k views' },
        { id: 'worst',      label: 'Lowest Performing',        type: 'text',  placeholder: 'Static quote post - 200 reach' },
        { id: 'insights',   label: 'Key Insights & Actions',   type: 'textarea', placeholder: 'Video content 3x better than static...' },
      ]
    }
  ]
};

window.NICHE_META = {
  resumes:  { label: 'Resumes',      icon: '📄', color: '#E94560', bg: '#1A1A2E' },
  planners: { label: 'Planners',     icon: '📅', color: '#8BC34A', bg: '#2D4A22' },
  finance:  { label: 'Finance',      icon: '💰', color: '#F0A500', bg: '#0A3D62' },
  social:   { label: 'Social Media', icon: '📱', color: '#E91E8C', bg: '#4A0E2B' },
};
